### ISSUE TITLE
No sessionid

### ISSUE THREAD

**Issue by tsukasa1989** [Z0rdak/RepetierSharp#26]
It seems I don't get a sessionid. I can get the ServerInfoAsync. I try to activate the printer and then do a file upload.

When I Activate a printer, and do a `rc.SetTemperature(RepetierSharp.Models.Commands.TemperatureTarget.HeatedBed, 60);` there is nothing in the logs on the server.

In my UploadGCode, I get a response status code `StatusCode: NonAuthoritativeInformation`. And when I go to UploadModel it does not include a SessionId, because it is null.

Any tips on how to get a SessionId, because I think its mandatory.

This is my code:

              rc = new RepetierConnectionBuilder()
                .WithHost("localhost", 3344)
                .WithCredentials("global", "")
                .Build();

            rc.OnEvent += Rc_OnEvent;           

            rc.OnRepetierConnected += async () =>
            {
                Console.WriteLine("Connected!");

                var result = rc.GetRepetierServerInfoAsync().Result.Printers.Where(it => it.IsActive).ToList();
                if(result.Count > 0 )
                {
                    var printer = result.First().Slug;
                    rc.ActivatePrinter(printer);
                    Console.WriteLine("Activating printer: " + printer);
                    var bytes = System.IO.File.ReadAllBytes("C:\\Users\\Niels\\Desktop\\FP3D_Bottom_Closed_2mm_R_1686207369.gcode");
                    rc.UploadGCode("test.gcode", bytes, printer, "*", true);
                } else
                {
                    rc.Close();
                    rc = null;
                }
                
                //rc.EnqueueJob(6);
            };

            rc.Connect();

PS: I also used empty credentials, and no result.

**Comment by Z0rdak** [comment]
Hey there,

so it seems like you have already defined a user within your Repetier Server - could this be the case?

If you don't get a sessionId, this is most likely caused due to a failed authentication. An anonymous authentication at a Repetier-Server is not possible, when at least one other user profile is defined. 

The anonymous auth is the same as providing the credentials user `global` with an empty password.

Please check whether a user profile is defined at your server. An alternative to using the user credentials, you can also use the user-specific API-key. If you don't have a user defined, you can also try to use the global API key.

Also, I suggest adding some additional event handlers to get some more information (see below):


```csharp
var rc = new RepetierConnectionBuilder()
                .WithHost("localhost", 3344)
                // [...]
                .Build();

rc.OnEvent += (string eventName, string printer, IRepetierEvent repetierEvent) =>
{
	Console.WriteLine($"Log: {eventName} {printer}");
};

rc.OnLoginRequired += () =>
{
	Console.WriteLine("Server requires authentication. Attempting to login with supplied credentials..");
	// login is attempted automatically at this point when credentials are supplied 
};

rc.OnLoginResult += (loginMsg) =>
{
	Console.WriteLine($"Login: {(loginMsg.Authenticated ? "success" : "failed")}");
	Console.WriteLine(loginMsg);
};

rc.OnPermissionDenied += (cmdId) =>
{
	Console.WriteLine($"Permission denied for command with id: {cmdId}");
};

rc.OnRepetierConnected += async () =>
{
	Console.WriteLine("Connected!");

	var result = rc.GetRepetierServerInfoAsync().Result.Printers.Where(it => it.IsActive).ToList();
	if (result.Count > 0)
	{
		var printer = result.First().Slug;
		rc.ActivatePrinter(printer);
		Console.WriteLine("Activating printer: " + printer);

	}
	else
	{
		rc.Close();
		rc = null;
	}

	//rc.EnqueueJob(6);
};

rc.Connect();
```

Please try this and report back what works and what not. If you have any other issues, don't hesitate to ask.

Best regards

**Comment by tsukasa1989** [comment]
I installed a fresh server, no users. I removed the withCredentials part.
For the file upload: StatusCode: NonAuthoritativeInformation. 

The log from the logs above:

```
Log: userCredentials 
Log: modelGroupListChanged Test_printer
Log: jobsChanged Test_printer
Log: config Test_printer
```

For the File upload the SessionId is empty, probably that is the problem with the credentials

![image](https://github.com/Z0rdak/RepetierSharp/assets/1275050/83a391a3-f92d-40a8-8f22-18f3db4da6a0)


Regarding the Api Key, the upload gives status code OK, but the file is not visible on the server. I investigated why this happens, and the `UploadModel` uses the AddFile with name gcode, while I checked the developer tools in the server and they use the key filename. When I changed it to filename it worked: `.AddFile("filename", file, fileName)`.

My goal is to not use the api key, but the anonymous upload. Any suggestions with the above information?

**Comment by Z0rdak** [comment]
Thanks for the heads-up.

It's possible the parameter name for the file has changed between Repetier Server versions. I'll get a fix out asap. 

I've also found a solution regarding the missing `sessionId` with an anonymous session.  The sessionId from the websocket connection is not yet existing when you are trying to use the HTTP API. Usually you would use an api-key, when you don't have a sessionId. 

This was an edge case which I have missed. Sorry about that.

I've a workaround/fix for this in the next update. It will most likely be released this evening.

**Comment by tsukasa1989** [comment]
I use Repetier-Server Free 1.4.10 

For the SessionId I will wait for your update this evening then I can continue my work tomorrow.

Thank you for the great support.

**Comment by Z0rdak** [comment]
I've just published a new release 0.1.8.1 as nuget package and here in the repo.

I've tested it against the official demo servers and my own server. Hopefully this fixes your issue.

If not, feel free to report back/open a new issue. :)

Best regards

**Comment by tsukasa1989** [comment]
Thank you!  It works perfectly!

At the moment I need to download the source because my project is a bit older and I have .net 4.8. 
It's just small changes to make it compatible with .net 4.8.

**Comment by Z0rdak** [comment]
You are welcome! I am glad it works.

I'll consider changing these things to support older frameworks/standards.
